In [1]:
# Lodz University of Technology
# 2022-23 Image Processing Assignment 1
# @Ahmet Galip Sengun - 904261
# October 2022

# Task 1

In [2]:
import numpy as np
%matplotlib auto

Using matplotlib backend: <object object at 0x000002B1708F7920>


In [3]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
transposed_a = a.T
transposed_a

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

## Horizontal Flip

In [5]:
#horizontal
#np.flip(a, 1)
horizontal_flipped = a[:,::-1]
horizontal_flipped

array([[ 2,  1,  0],
       [ 5,  4,  3],
       [ 8,  7,  6],
       [11, 10,  9]])

## Vertical Flip

In [6]:
#vertical
#np.flip(a, 0)
vertical_flipped = a[::-1,:]
vertical_flipped

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

## Rotation by 180'

In [7]:
#180 degree
rotated_180 = a[::-1,::-1]
rotated_180

array([[11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

## Rotation by 90' right

In [8]:
#90 degrees to the right
rotated_90l = rotated_180.T[::-1,:]
rotated_90l

array([[ 9,  6,  3,  0],
       [10,  7,  4,  1],
       [11,  8,  5,  2]])

## Rotation by 90' left

In [9]:
#90 degrees to the left
rotated_90r = a.T[::-1,:]
rotated_90r

array([[ 2,  5,  8, 11],
       [ 1,  4,  7, 10],
       [ 0,  3,  6,  9]])

## Extend Function

returning an extended matrix of size M x M (if M != N) or unchanged matrix (otherwise). In the former case, added parts should be zeroed

In [10]:
def extend(a):
    rows, cols = np.shape(a)

    if rows == cols:
        return a
    
    elif rows > cols:
        diff = rows - cols
        
        if diff == 1:
            zeros = np.zeros(rows).reshape(rows, 1)
            new = np.hstack((a, zeros))

        else:
            zeros = np.zeros(rows*(diff//2)).reshape(rows, (diff//2))
            new = np.hstack((a, zeros))
            new = np.hstack((zeros, new))
            if diff%2 == 1:
                zeros = np.zeros(rows).reshape(rows, 1)
                new = np.hstack((zeros, new))
        
    elif cols > rows:
        diff = cols - rows
        
        if diff == 1:
            zeros = np.zeros(cols)
            new = np.vstack((a, zeros))
        else:
            zeros = np.zeros(cols*(diff//2)).reshape((diff//2), cols)
            new = np.vstack((a, zeros))
            new = np.vstack((zeros, new))
            if diff%2 == 1:
                zeros = np.zeros(cols)
                new = np.vstack((new, zeros))
           
            
    return new

### Extend function example

In [11]:
a = np.arange(18).reshape(6,3)
print(extend(a))
print(np.shape(extend(a)))

[[ 0.  0.  0.  1.  2.  0.]
 [ 0.  0.  3.  4.  5.  0.]
 [ 0.  0.  6.  7.  8.  0.]
 [ 0.  0.  9. 10. 11.  0.]
 [ 0.  0. 12. 13. 14.  0.]
 [ 0.  0. 15. 16. 17.  0.]]
(6, 6)


## Reduce Function

returning a truncated matrix of size N x N (if M != N) or unchanged matrix (otherwise). In the former case  leave exactly N middle columns/rows.


In [12]:
def reduce(a):
    rows, cols = np.shape(a)
    
    if rows == cols:
        return a
    
    elif rows > cols:
        diff = rows - cols
        
        if diff == 1:
            new = a[1:,]
            
        elif diff%2 == 0:
            new = a[diff//2:-(diff//2),]
            
        else:
            new = a[(diff//2)+1:-(diff//2),]
            
    else:
        diff = cols - rows
        
        if diff == 1:
            new = a[:,1:]
            
        elif diff%2 == 0:
            new = a[:,diff//2:-(diff//2)]
            
        else:
            new = a[:,(diff//2)+1:-(diff//2)]
            
    
    return new

### Reduce function example

In [13]:
rows, cols = 4, 10
a = np.arange(rows*cols).reshape(rows,cols)
print(reduce(a))
print(np.shape(reduce(a)))

[[ 3  4  5  6]
 [13 14 15 16]
 [23 24 25 26]
 [33 34 35 36]]
(4, 4)


# Task 2

In [14]:
import cv2
import numpy as np

#Load image
img = cv2.imread("Lena.jpg")

In [15]:
img.shape

(670, 1082, 3)

### Display Image

In [16]:
cv2.imshow("Colored image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Display Grayscale Image

In [17]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow('Gray image', gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Blank Image 640x480

In [18]:
blank_image = np.zeros((640,480,3), np.uint8)

In [19]:
cv2.imshow("blank image",blank_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Paste Lena Into the Blank Image

In [20]:
def fit_into_blank(img, blank_image):
    height, width, _ = blank_image.shape
    img_height, img_width, _ = img.shape
    
    width_diff = img_width - width
    height_diff = img_height - height
    
    img = img[height_diff//2:-height_diff//2,width_diff//2:-width_diff//2,:]
    
    blank_image = cv2.add(blank_image, img)
    
    return blank_image

In [21]:
new = fit_into_blank(img, blank_image)
cv2.imshow('Blank image', new)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Task 3

In [22]:
import cv2
import numpy as np
img = cv2.imread("Lena.jpg")

In [23]:
width, height, _ = img.shape
width, height

(670, 1082)

### Crop & Make it Square

In [24]:
diff = height - width

if diff > 0:
    square_img = img[:,diff//2:-diff//2,:]
else:
    diff = -diff
    square_img = img[diff//2:-diff//2,:,:]
square_img.shape

(670, 670, 3)

In [25]:
cv2.imshow('Square image', square_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Split Image Into Pieces

In [26]:
def fix_sizes(img, n_division):
    width, _, _ = img.shape
    diff = width % n_division
    img = img[diff:,diff:,]
    return img

In [27]:
#testing the fix_sizes function
img_ = fix_sizes(square_img, 3)
img_.shape

(669, 669, 3)

In [28]:
import random

def shuffle_img(img, n):
    img = fix_sizes(img, n)
    shape = img.shape
    
    img = fix_sizes(img, n)
    
    M = img.shape[0]//n
    N = img.shape[1]//n
    
    tiles = [img[x:x+M,y:y+N] for x in range(0,img.shape[0],M) for y in range(0,img.shape[1],N)]
    random.shuffle(tiles)
    tiles = np.array(tiles)
    
    h_img = []
    for i in range(0, n*n, n):
        h_img.append(cv2.hconcat(tiles[i:i+n]))
    
    v_img = cv2.vconcat(h_img)


    
    return np.array(v_img)

### Display shuffled image

In [29]:
n = 7
cv2.imshow('Shuffled image', shuffle_img(square_img, n))
cv2.waitKey(0)
cv2.destroyAllWindows()